- name: variable to print 
  hosts: web
  vars: 
    COURSE : "Devops"
    DURATION: "120"
  tasks:
  - name: Print the Information
    ansible.builtin.debug:
      msg: "Hi {{COURSE}} and {{DURATION}}"
  tasks:
  - name: task level override
    vars:
        COURSE: "Jenkins"
    ansible.builtin.debug:
      msg: "Hi {{COURSE}}"