- name: Variable call
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: DURATION
    prompt: please enter the course duration
  tasks:
  - name: print course
    ansible.builtin.debug:
      msg: "It is {{COURSE}}, {{DURATION}}"